var EKG_SEARCH_DATA = [
  { title: 'Car Emergency Kit', desc: 'Complete guide to roadside preparedness and essential gear', url: '/car-emergency-kit/', category: 'Kits', icon: 'car' },
  { title: 'Fire Emergency Kit', desc: 'Home fire safety equipment and escape planning essentials', url: '/fire-emergency-kit/', category: 'Kits', icon: 'fire' },
  { title: '72-Hour Survival Kit', desc: 'Build a three-day survival kit step by step', url: '/guides/72-hour-kit/', category: 'Guides', icon: 'clock' },
  { title: 'Home Emergency Kit', desc: 'Complete household emergency preparedness guide', url: '/guides/home-emergency-kit/', category: 'Guides', icon: 'home' },
  { title: 'First Aid Kit Guide', desc: 'Medical emergency response essentials and kit contents', url: '/guides/first-aid/', category: 'Guides', icon: 'medical' },
  { title: 'Natural Disaster Preparedness', desc: 'Hurricanes, earthquakes, floods, and severe weather', url: '/guides/natural-disasters/', category: 'Guides', icon: 'alert' },
  { title: 'Winter Emergency Kit', desc: 'Cold weather survival and winter storm preparedness', url: '/guides/winter-kit/', category: 'Guides', icon: 'snow' },
  { title: 'Bug-Out Bag Guide', desc: 'Build the ultimate grab-and-go survival bag', url: '/guides/bug-out-bag/', category: 'Guides', icon: 'pack' },
  { title: 'Emergency Checklists', desc: 'Interactive checklist generator for every situation', url: '/checklists/', category: 'Tools', icon: 'check' },
  { title: 'Car Emergency Checklist', desc: 'Roadside emergency essentials checklist', url: '/checklists/car/', category: 'Checklists', icon: 'check' },
  { title: 'Fire Emergency Checklist', desc: 'Home fire safety and escape checklist', url: '/checklists/fire/', category: 'Checklists', icon: 'check' },
  { title: 'Winter Emergency Checklist', desc: 'Cold weather survival checklist', url: '/checklists/winter/', category: 'Checklists', icon: 'check' },
  { title: 'Storm Emergency Checklist', desc: 'Severe weather and storm preparedness checklist', url: '/checklists/storm/', category: 'Checklists', icon: 'check' },
  { title: 'Travel Emergency Checklist', desc: 'Travel safety and emergency preparedness checklist', url: '/checklists/travel/', category: 'Checklists', icon: 'check' },
  { title: 'Family Emergency Checklist', desc: 'Family preparedness and safety checklist', url: '/checklists/family/', category: 'Checklists', icon: 'check' },
  { title: 'Emergency FAQs', desc: 'Answers to common emergency preparedness questions', url: '/faq/', category: 'FAQs', icon: 'question' },
  { title: 'About EmergencyKitGuide', desc: 'Our mission, editorial policy, and content standards', url: '/about/', category: 'About', icon: 'info' },
  { title: 'Contact Us', desc: 'Get in touch with our team', url: '/contact/', category: 'Contact', icon: 'mail' },
  { title: 'Water Storage Guide', desc: 'How to store water for emergencies', url: '/guides/water-storage/', category: 'Guides', icon: 'droplet' },
  { title: 'Emergency Communication Plan', desc: 'Family communication strategies during disasters', url: '/guides/communication-plan/', category: 'Guides', icon: 'radio' },
  { title: 'Food Storage for Emergencies', desc: 'Long-term food storage and emergency nutrition', url: '/guides/food-storage/', category: 'Guides', icon: 'food' },
  { title: 'Pet Emergency Kit', desc: 'Emergency preparedness for your pets', url: '/guides/pet-emergency-kit/', category: 'Guides', icon: 'pet' },
  { title: 'Power Outage Kit', desc: 'Essentials for extended power outages', url: '/guides/power-outage-kit/', category: 'Guides', icon: 'bolt' },
  { title: 'How many emergency kits should I have?', desc: 'Expert answer on emergency kit quantities', url: '/faq/#kits-count', category: 'FAQs', icon: 'question' },
  { title: 'How often should I update my emergency kit?', desc: 'Expert answer on emergency kit maintenance', url: '/faq/#kits-update', category: 'FAQs', icon: 'question' },
  { title: 'What is the most important emergency item?', desc: 'Expert answer on essential emergency items', url: '/faq/#most-important', category: 'FAQs', icon: 'question' }
];