var EKG_SEARCH_DATA = [
  { title: 'Car Emergency Kit', desc: 'Complete guide to roadside preparedness and essential gear', url: '/car-emergency-kit/', category: 'Kits', icon: 'car' },
  { title: 'Fire Emergency Kit', desc: 'Home fire safety equipment and escape planning essentials', url: '/fire-emergency-kit/', category: 'Kits', icon: 'fire' },
  { title: '72-Hour Survival Kit', desc: 'Build a three-day survival kit step by step', url: '/guides/72-hour-kit/', category: 'Guides', icon: 'clock' },
  { title: 'Home Emergency Kit', desc: 'Complete household emergency preparedness guide', url: '/guides/home-emergency-kit/', category: 'Guides', icon: 'home' },
  { title: 'First Aid Kit Guide', desc: 'Medical emergency response essentials and kit contents', url: '/guides/first-aid/', category: 'Guides', icon: 'medical' },
  { title: 'Natural Disaster Preparedness', desc: 'Hurricanes, earthquakes, floods, and severe weather', url: '/guides/natural-disasters/', category: 'Guides', icon: 'alert' },
  { title: 'Winter Emergency Kit', desc: 'Cold weather survival and winter storm preparedness', url: '/guides/winter-kit/', category: 'Guides', icon: 'snow' },
  { title: 'Bug-Out Bag Guide', desc: 'Build the ultimate grab-and-go survival bag', url: '/guides/bug-out-bag/', category: 'Guides', icon: 'pack' },
  { title: 'Emergency Checklists', desc: 'Interactive checklist generator for every situation', url: '/checklists/', category: 'Tools', icon: 'check' },
  { title: 'Car Emergency Checklist', desc: 'Roadside emergency essentials checklist', url: '/checklists/car/', category: 'Checklists', icon: 'check' },
  { title: 'Fire Emergency Checklist', desc: 'Home fire safety and escape checklist', url: '/checklists/fire/', category: 'Checklists', icon: 'check' },
  { title: 'Winter Emergency Checklist', desc: 'Cold weather survival checklist', url: '/checklists/winter/', category: 'Checklists', icon: 'check' },
  { title: 'Storm Emergency Checklist', desc: 'Severe weather and storm preparedness checklist', url: '/checklists/storm/', category: 'Checklists', icon: 'check' },
  { title: 'Travel Emergency Checklist', desc: 'Travel safety and emergency preparedness checklist', url: '/checklists/travel/', category: 'Checklists', icon: 'check' },
  { title: 'Family Emergency Checklist', desc: 'Family preparedness and safety checklist', url: '/checklists/family/', category: 'Checklists', icon: 'check' },
  { title: 'Emergency FAQs', desc: 'Answers to common emergency preparedness questions', url: '/faq/', category: 'FAQs', icon: 'question' },
  { title: 'About EmergencyKitGuide', desc: 'Our mission, editorial policy, and content standards', url: '/about/', category: 'About', icon: 'info' },
  { title: 'Contact Us', desc: 'Get in touch with our team', url: '/contact/', category: 'Contact', icon: 'mail' },
  { title: 'Water Storage Guide', desc: 'How to store water for emergencies', url: '/guides/water-storage/', category: 'Guides', icon: 'droplet' },
  { title: 'Emergency Communication Plan', desc: 'Family communication strategies during disasters', url: '/guides/communication-plan/', category: 'Guides', icon: 'radio' },
  { title: 'Food Storage for Emergencies', desc: 'Long-term food storage and emergency nutrition', url: '/guides/food-storage/', category: 'Guides', icon: 'food' },
  { title: 'Pet Emergency Kit', desc: 'Emergency preparedness for your pets', url: '/guides/pet-emergency-kit/', category: 'Guides', icon: 'pet' },
  { title: 'Power Outage Kit', desc: 'Essentials for extended power outages', url: '/guides/power-outage-kit/', category: 'Guides', icon: 'bolt' },
  { title: 'How many emergency kits should I have?', desc: 'Expert answer on emergency kit quantities', url: '/faq/#kits-count', category: 'FAQs', icon: 'question' },
  { title: 'How often should I update my emergency kit?', desc: 'Expert answer on emergency kit maintenance', url: '/faq/#kits-update', category: 'FAQs', icon: 'question' },
  { title: 'What is the most important emergency item?', desc: 'Expert answer on essential emergency items', url: '/faq/#most-important', category: 'FAQs', icon: 'question' },
  { title: 'Car Emergency Kit Essentials', desc: 'Complete checklist of essential items every driver should carry', url: '/guides/car-emergency-kit-essentials/', category: 'Guides', icon: 'car' },
  { title: 'Car First Aid Kit Guide', desc: 'What every driver needs in a car first aid kit', url: '/guides/car-first-aid-kit/', category: 'Guides', icon: 'medical' },
  { title: 'Roadside Emergency Preparedness', desc: 'How to handle any roadside emergency with confidence', url: '/guides/roadside-emergency-preparedness/', category: 'Guides', icon: 'car' },
  { title: 'Free Car Emergency Kit', desc: 'Build a car emergency kit from items you already own', url: '/guides/free-car-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Winter Car Emergency Kit', desc: 'Essential cold-weather survival gear for your vehicle', url: '/guides/winter-car-emergency-kit/', category: 'Guides', icon: 'snow' },
  { title: 'Summer Car Emergency Kit', desc: 'Beat the heat and stay safe during hot-weather driving', url: '/guides/summer-car-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Road Trip Emergency Kit', desc: 'Everything you need for long-distance travel safety', url: '/guides/road-trip-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Fire Extinguisher Types', desc: 'Choosing the right fire extinguisher for every situation', url: '/guides/fire-extinguisher-types/', category: 'Guides', icon: 'fire' },
  { title: 'Smoke Detector Placement', desc: 'Where to install smoke detectors for maximum protection', url: '/guides/smoke-detector-placement/', category: 'Guides', icon: 'fire' },
  { title: 'Fire Escape Plan for Families', desc: 'Create a reliable fire escape plan for your household', url: '/guides/fire-escape-plan-family/', category: 'Guides', icon: 'fire' },
  { title: 'Car Breakdown Survival Guide', desc: 'What to do when your car breaks down on the road', url: '/guides/car-breakdown-survival/', category: 'Guides', icon: 'car' },
  { title: 'Car Safety Essentials', desc: 'Critical safety items every vehicle should have', url: '/guides/car-safety-essentials/', category: 'Guides', icon: 'car' },
  { title: 'Apartment Fire Safety', desc: 'Fire safety tips for apartment dwellers', url: '/guides/apartment-fire-safety/', category: 'Guides', icon: 'fire' },
  { title: 'Home Fire Prevention Tips', desc: 'Prevent fires before they start in your home', url: '/guides/home-fire-prevention-tips/', category: 'Guides', icon: 'fire' },
  { title: 'Kitchen Fire Safety Guide', desc: 'Protect your kitchen from fire hazards', url: '/guides/kitchen-fire-safety-guide/', category: 'Guides', icon: 'fire' },
  { title: 'Wildfire Preparedness Guide', desc: 'Stay safe during wildfire season and evacuation', url: '/guides/wildfire-preparedness-guide/', category: 'Guides', icon: 'fire' },
  { title: 'Home Fire Emergency Kit', desc: 'What every household needs for fire safety, detection, escape, and survival', url: '/guides/home-fire-emergency-kit/', category: 'Guides', icon: 'fire' },
  { title: 'Wildfire Emergency Kit', desc: 'Go-bags, N95 masks, evacuation planning, and wildfire season preparation', url: '/guides/wildfire-emergency-kit/', category: 'Guides', icon: 'fire' },
  { title: 'Apartment Fire Emergency Kit', desc: 'Fire safety essentials for renters with damage-free mounting solutions', url: '/guides/apartment-fire-emergency-kit/', category: 'Guides', icon: 'fire' },
  { title: 'Fire Evacuation Plan', desc: 'Step-by-step guide to escape routes, meeting spots, and family fire drills', url: '/guides/fire-evacuation-plan/', category: 'Guides', icon: 'fire' },
  { title: 'Fire Safety Supplies', desc: 'Complete checklist of detection, suppression, escape, and protection gear', url: '/guides/fire-safety-supplies/', category: 'Guides', icon: 'fire' },
  { title: 'Teen Driver Emergency Kit', desc: 'Essential emergency kit items every new teen driver should carry', url: '/guides/teen-driver-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Car Emergency Kit Checklist', desc: 'Printable checklist covering every essential item for roadside emergencies', url: '/guides/car-emergency-kit-checklist/', category: 'Guides', icon: 'car' },
  { title: 'Replace Car Emergency Kit Supplies', desc: 'When and how to replace expired or degraded car emergency kit items', url: '/guides/replace-car-emergency-kit-supplies/', category: 'Guides', icon: 'car' },
  { title: 'Car Emergency Kit FAQ', desc: 'Answers to every car emergency kit question from cost to storage', url: '/guides/car-emergency-kit-faq/', category: 'Guides', icon: 'car' },
  { title: 'Power Outage Checklist', desc: 'Complete checklist for surviving blackouts with lighting, food, and safety supplies', url: '/checklists/power-outage/', category: 'Checklists', icon: 'check' },
  { title: 'Winter Storm Checklist', desc: 'Step-by-step preparation before, during, and after winter storms', url: '/checklists/winter-storm/', category: 'Checklists', icon: 'check' }
];