var EKG_SEARCH_DATA = [
  { title: 'EmergencyKitHQ', desc: 'Expert guides, checklists, and recommendations for building the perfect emergency kit', url: '/', category: 'Home', icon: 'home' },
  { title: 'Car Emergency Kit', desc: 'Complete guide to roadside preparedness and essential gear', url: '/car-emergency-kit/', category: 'Kits', icon: 'car' },
  { title: 'Fire Emergency Kit', desc: 'Home fire safety equipment and escape planning essentials', url: '/fire-emergency-kit/', category: 'Kits', icon: 'fire' },
  { title: '72-Hour Survival Kit', desc: 'Build a three-day survival kit step by step', url: '/guides/72-hour-kit/', category: 'Guides', icon: 'clock' },
  { title: 'Home Emergency Kit', desc: 'Complete household emergency preparedness guide', url: '/guides/home-emergency-kit/', category: 'Guides', icon: 'home' },
  { title: 'Emergency Checklists', desc: 'Interactive checklist generator for every situation', url: '/checklists/', category: 'Tools', icon: 'check' },
  { title: 'Car Emergency Checklist', desc: 'Roadside emergency essentials checklist', url: '/checklists/car/', category: 'Checklists', icon: 'check' },
  { title: 'Winter Car Emergency Kit Checklist', desc: 'Cold weather survival checklist', url: '/checklists/winter/', category: 'Checklists', icon: 'check' },
  { title: 'Winter Storm Emergency Checklist', desc: 'Step-by-step preparation before, during, and after winter storms', url: '/checklists/winter-storm/', category: 'Checklists', icon: 'check' },
  { title: 'Storm Emergency Checklist', desc: 'Severe weather and storm preparedness checklist', url: '/checklists/storm/', category: 'Checklists', icon: 'check' },
  { title: 'Travel Emergency Checklist', desc: 'Travel safety and emergency preparedness checklist', url: '/checklists/travel/', category: 'Checklists', icon: 'check' },
  { title: 'Family Emergency Checklist', desc: 'Family preparedness and safety checklist', url: '/checklists/family/', category: 'Checklists', icon: 'check' },
  { title: 'Emergency FAQs', desc: 'Answers to common emergency preparedness questions', url: '/faq/', category: 'FAQs', icon: 'question' },
  { title: 'Emergency Preparedness Guides', desc: 'Browse all guides for car, fire, home, and wilderness emergency preparedness', url: '/guides/', category: 'Guides', icon: 'info' },
  { title: 'About EmergencyKitHQ', desc: 'Our mission, editorial policy, and content standards', url: '/about/', category: 'About', icon: 'info' },
  { title: 'Contact Us', desc: 'Get in touch with our team', url: '/contact/', category: 'Contact', icon: 'mail' },

  { title: 'Car Emergency Kit Essentials', desc: 'Complete checklist of essential items every driver should carry', url: '/guides/car-emergency-kit-essentials/', category: 'Guides', icon: 'car' },
  { title: 'Car First Aid Kit Guide', desc: 'What every driver needs in a car first aid kit', url: '/guides/car-first-aid-kit/', category: 'Guides', icon: 'medical' },
  { title: 'Roadside Emergency Preparedness', desc: 'How to handle any roadside emergency with confidence', url: '/guides/roadside-emergency-preparedness/', category: 'Guides', icon: 'car' },
  { title: 'Free Car Emergency Kit', desc: 'Build a car emergency kit from items you already own', url: '/guides/free-car-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Winter Car Emergency Kit', desc: 'Essential cold-weather survival gear for your vehicle', url: '/guides/winter-car-emergency-kit/', category: 'Guides', icon: 'snow' },
  { title: 'Summer Car Emergency Kit', desc: 'Beat the heat and stay safe during hot-weather driving', url: '/guides/summer-car-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Road Trip Emergency Kit', desc: 'Everything you need for long-distance travel safety', url: '/guides/road-trip-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Road Trip Car Emergency Kit', desc: 'Long-distance road trip safety essentials and preparation', url: '/guides/road-trip-car-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Fire Extinguisher Types', desc: 'Choosing the right fire extinguisher for every situation', url: '/guides/fire-extinguisher-types/', category: 'Guides', icon: 'fire' },
  { title: 'Smoke Detector Placement', desc: 'Where to install smoke detectors for maximum protection', url: '/guides/smoke-detector-placement/', category: 'Guides', icon: 'fire' },
  { title: 'Fire Escape Plan for Families', desc: 'Create a reliable fire escape plan for your household', url: '/guides/fire-escape-plan-family/', category: 'Guides', icon: 'fire' },
  { title: 'Car Breakdown Survival Guide', desc: 'What to do when your car breaks down on the road', url: '/guides/car-breakdown-survival/', category: 'Guides', icon: 'car' },
  { title: 'Car Safety Essentials', desc: 'Critical safety items every vehicle should have', url: '/guides/car-safety-essentials/', category: 'Guides', icon: 'car' },
  { title: 'Apartment Fire Safety', desc: 'Fire safety tips for apartment dwellers', url: '/guides/apartment-fire-safety/', category: 'Guides', icon: 'fire' },
  { title: 'Home Fire Prevention Tips', desc: 'Prevent fires before they start in your home', url: '/guides/home-fire-prevention-tips/', category: 'Guides', icon: 'fire' },
  { title: 'Kitchen Fire Safety Guide', desc: 'Protect your kitchen from fire hazards', url: '/guides/kitchen-fire-safety-guide/', category: 'Guides', icon: 'fire' },
  { title: 'Wildfire Preparedness Guide', desc: 'Stay safe during wildfire season and evacuation', url: '/guides/wildfire-preparedness-guide/', category: 'Guides', icon: 'fire' },
  { title: 'Home Fire Emergency Kit', desc: 'What every household needs for fire safety, detection, escape, and survival', url: '/guides/home-fire-emergency-kit/', category: 'Guides', icon: 'fire' },
  { title: 'Wildfire Emergency Kit', desc: 'Go-bags, N95 masks, evacuation planning, and wildfire season preparation', url: '/guides/wildfire-emergency-kit/', category: 'Guides', icon: 'fire' },
  { title: 'Apartment Fire Emergency Kit', desc: 'Fire safety essentials for renters with damage-free mounting solutions', url: '/guides/apartment-fire-emergency-kit/', category: 'Guides', icon: 'fire' },
  { title: 'Fire Evacuation Plan', desc: 'Step-by-step guide to escape routes, meeting spots, and family fire drills', url: '/guides/fire-evacuation-plan/', category: 'Guides', icon: 'fire' },
  { title: 'Fire Safety Supplies', desc: 'Complete checklist of detection, suppression, escape, and protection gear', url: '/guides/fire-safety-supplies/', category: 'Guides', icon: 'fire' },
  { title: 'Teen Driver Emergency Kit', desc: 'Essential emergency kit items every new teen driver should carry', url: '/guides/teen-driver-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Car Emergency Kit Checklist', desc: 'Printable checklist covering every essential item for roadside emergencies', url: '/guides/car-emergency-kit-checklist/', category: 'Guides', icon: 'car' },
  { title: 'Replace Car Emergency Kit Supplies', desc: 'When and how to replace expired or degraded car emergency kit items', url: '/guides/replace-car-emergency-kit-supplies/', category: 'Guides', icon: 'car' },
  { title: 'Car Emergency Kit FAQ', desc: 'Answers to every car emergency kit question from cost to storage', url: '/guides/car-emergency-kit-faq/', category: 'Guides', icon: 'car' },
  { title: 'Family Car Emergency Kit', desc: 'Keeping everyone safe during roadside emergencies with kids', url: '/guides/family-car-emergency-kit/', category: 'Guides', icon: 'car' },
  { title: 'Office Emergency Checklist', desc: 'Workplace safety supplies for fires, evacuations, medical emergencies, and severe weather', url: '/checklists/office/', category: 'Checklists', icon: 'check' },
  { title: 'Power Outage Checklist', desc: 'Complete checklist for surviving blackouts with lighting, food, and safety supplies', url: '/checklists/power-outage/', category: 'Checklists', icon: 'check' },
  { title: 'Home Emergency Checklist', desc: 'Complete home emergency checklist for earthquakes, fires, and storms', url: '/checklists/home/', category: 'Checklists', icon: 'check' },
  { title: 'Pet Emergency Checklist', desc: 'Emergency supplies and evacuation planning for dogs, cats, and exotic pets', url: '/checklists/pet/', category: 'Checklists', icon: 'check' },
  { title: 'Vehicle Emergency Checklist', desc: 'Roadside repair tools, safety gear, and emergency supplies for every driver', url: '/checklists/vehicle/', category: 'Checklists', icon: 'check' },
  { title: 'First Aid Emergency Checklist', desc: 'Complete medical supplies for wound care, CPR, burns, fractures, and severe bleeding', url: '/checklists/first-aid/', category: 'Checklists', icon: 'check' },
  { title: 'Bug Out Bag Checklist', desc: '72-hour survival gear packed and ready for emergency evacuation', url: '/checklists/bug-out-bag/', category: 'Checklists', icon: 'check' },
  { title: 'Editorial Process', desc: 'How we research, write, review, and update every guide', url: '/editorial/', category: 'About', icon: 'info' },
  { title: 'Review Policy', desc: 'How we test, rate, and recommend emergency preparedness products', url: '/reviews/', category: 'About', icon: 'info' },
  { title: 'Blog', desc: 'Browse all emergency preparedness guides, checklists, and resources', url: '/blog/', category: 'Guides', icon: 'info' },
  { title: 'Disclaimer', desc: 'Legal disclaimer and content limitations', url: '/disclaimer/', category: 'About', icon: 'info' },
  { title: 'Privacy Policy', desc: 'How we collect, use, and protect your information', url: '/privacy-policy/', category: 'About', icon: 'info' },
  { title: 'Terms of Service', desc: 'Terms and conditions for using EmergencyKitHQ', url: '/terms/', category: 'About', icon: 'info' },
  { title: 'Affiliate Disclosure', desc: 'Our affiliate relationships and how they support our content', url: '/affiliate-disclosure/', category: 'About', icon: 'info' },
  { title: 'Emergency Kit Builder', desc: 'Build a personalized emergency kit checklist with our interactive tool', url: '/tools/emergency-kit-builder/', category: 'Tools', icon: 'tool' },
  { title: 'Family 72-Hour Emergency Kit', desc: 'Complete guide to building a 72-hour kit for every family member', url: '/guides/family-72-hour-emergency-kit/', category: 'Guides', icon: 'info' },
  { title: '72-Hour Kit for Kids', desc: 'Age-appropriate emergency supplies and comfort items for children', url: '/guides/72-hour-kit-for-kids/', category: 'Guides', icon: 'info' },
  { title: '72-Hour Emergency Food List', desc: 'Shelf-stable food options and calorie planning for 3-day emergencies', url: '/guides/72-hour-emergency-food-list/', category: 'Guides', icon: 'info' },
  { title: '72-Hour Water Storage Guide', desc: 'How much water to store, containers, purification, and rotation', url: '/guides/72-hour-water-storage-guide/', category: 'Guides', icon: 'info' },
  { title: '72-Hour Kit Checklist', desc: 'Complete printable checklist for 3-day emergency preparedness', url: '/guides/72-hour-kit-checklist-pdf/', category: 'Guides', icon: 'check' },
  { title: 'Emergency Preparedness Checklist', desc: 'Step-by-step supplies, communication plans, and disaster readiness', url: '/guides/emergency-preparedness-checklist/', category: 'Guides', icon: 'check' },
  { title: 'Disaster Preparedness Plan', desc: 'Risk assessment, family communication plans, and evacuation routes', url: '/guides/disaster-preparedness-plan/', category: 'Guides', icon: 'info' },
  { title: 'Home Evacuation Checklist', desc: 'What to grab, documents to save, and how to evacuate safely', url: '/guides/home-evacuation-checklist/', category: 'Guides', icon: 'check' },
  { title: 'Emergency Supplies List', desc: 'Essential items for home preparedness covering water, food, and tools', url: '/guides/emergency-supplies-list/', category: 'Guides', icon: 'check' },
  { title: 'Emergency Food Storage', desc: 'Beginner guide to shelf-stable foods, rotation, and calorie planning', url: '/guides/emergency-food-storage/', category: 'Guides', icon: 'info' },
  { title: 'Smoke Alarm Maintenance', desc: 'Testing, battery replacement, placement rules, and when to replace', url: '/guides/smoke-alarm-maintenance/', category: 'Guides', icon: 'fire' },
  { title: 'Fire Blanket Guide', desc: 'How to use, choose, and store fire blankets for kitchen safety', url: '/guides/fire-blanket-guide/', category: 'Guides', icon: 'fire' },
  { title: 'Carbon Monoxide Detector Guide', desc: 'Placement, testing, battery schedules, and what alerts mean', url: '/guides/carbon-monoxide-detector-guide/', category: 'Guides', icon: 'fire' },
  { title: 'Wildfire Evacuation Checklist', desc: 'Go-bag essentials, documents, pet supplies, and when to leave', url: '/guides/wildfire-evacuation-checklist/', category: 'Guides', icon: 'fire' },
  { title: 'Apartment Emergency Plan', desc: 'Fire escape routes, supplies for small spaces, and renter safety tips', url: '/guides/apartment-emergency-plan/', category: 'Guides', icon: 'home' },
  { title: 'Earthquake Emergency Kit', desc: 'Essential supplies for seismic events including dust masks, pry bars, and whistles', url: '/guides/earthquake-emergency-kit/', category: 'Guides', icon: 'info' },
  { title: 'Earthquake Preparedness Checklist', desc: 'Step-by-step seismic safety covering home securing, gas shutoff, and drills', url: '/guides/earthquake-preparedness-checklist/', category: 'Guides', icon: 'check' },
  { title: 'Earthquake Family Emergency Plan', desc: 'Communication trees, meeting points, and reunion strategies for families', url: '/guides/earthquake-family-plan/', category: 'Guides', icon: 'info' },
  { title: 'Hurricane Emergency Kit', desc: 'Complete storm preparedness supplies for 7+ day hurricane outages', url: '/guides/hurricane-emergency-kit/', category: 'Guides', icon: 'info' },
  { title: 'Hurricane Preparedness Checklist', desc: 'Before, during, and after steps for storm season readiness', url: '/guides/hurricane-preparedness-checklist/', category: 'Guides', icon: 'check' },
  { title: 'Hurricane Evacuation Plan', desc: 'Route planning, timing strategies, and go-bag packing for evacuation', url: '/guides/hurricane-evacuation-plan/', category: 'Guides', icon: 'info' },
  { title: 'Tornado Emergency Kit', desc: 'Storm shelter supplies, hard hats, and go-bags for tornado season', url: '/guides/tornado-emergency-kit/', category: 'Guides', icon: 'info' },
  { title: 'Tornado Safety Checklist', desc: 'Before, during, and after tornado safety steps for your family', url: '/guides/tornado-safety-checklist/', category: 'Guides', icon: 'check' },
  { title: 'Tornado Shelter Guide', desc: 'Safe rooms, basements, and underground shelter options compared', url: '/guides/tornado-shelter-guide/', category: 'Guides', icon: 'info' },
  { title: 'Flood Emergency Kit', desc: 'Water-resistant supplies and evacuation essentials for rising waters', url: '/guides/flood-emergency-kit/', category: 'Guides', icon: 'info' },
  { title: 'Flood Preparedness Guide', desc: 'Home protection, insurance, sandbagging, and evacuation planning', url: '/guides/flood-preparedness-guide/', category: 'Guides', icon: 'info' },
  { title: 'Flood Evacuation Checklist', desc: 'Warning levels, go-bag essentials, and safe evacuation routes for floods', url: '/guides/flood-evacuation-checklist/', category: 'Guides', icon: 'check' },
  { title: 'Emergency Power Backup Guide', desc: 'Generators, battery stations, and solar options for power outages', url: '/guides/emergency-power-backup-guide/', category: 'Guides', icon: 'info' },
  { title: 'Blackout Food Storage', desc: 'Keeping food safe during extended power outages with no-cook options', url: '/guides/blackout-food-storage/', category: 'Guides', icon: 'info' },
  { title: 'Emergency Water Storage Guide', desc: 'Containers, purification methods, and rotation schedules for water storage', url: '/guides/emergency-water-storage-guide/', category: 'Guides', icon: 'info' },
  { title: 'Emergency Plan for Families', desc: 'Complete household disaster preparedness with communication and evacuation', url: '/guides/emergency-plan-for-families/', category: 'Guides', icon: 'info' },
  { title: 'Emergency Kit for Seniors', desc: 'Customized supplies for elderly preparedness including medical and mobility', url: '/guides/emergency-kit-for-seniors/', category: 'Guides', icon: 'info' },
  { title: 'Emergency Kit for Babies', desc: 'Infant and toddler emergency supplies including formula, diapers, and safety', url: '/guides/emergency-kit-for-babies/', category: 'Guides', icon: 'info' },
  { title: 'Emergency Communication Plan', desc: 'Family contact trees, two-way radios, and staying connected during disasters', url: '/guides/emergency-communication-plan/', category: 'Guides', icon: 'info' },
  { title: 'Disaster Supply Checklist', desc: 'Universal emergency preparedness inventory for any disaster scenario', url: '/guides/disaster-supply-checklist/', category: 'Guides', icon: 'check' },
  { title: 'Emergency Kit California', desc: 'State-specific disaster preparedness for earthquakes, wildfires, and extreme heat', url: '/guides/emergency-kit-california/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Texas', desc: 'Hurricane, tornado, and extreme heat preparedness for Texas residents', url: '/guides/emergency-kit-texas/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Florida', desc: 'Hurricane season, storm surge, and tropical storm preparedness for Florida', url: '/guides/emergency-kit-florida/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit New York', desc: 'Urban and coastal disaster preparedness for New York residents', url: '/guides/emergency-kit-new-york/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Pennsylvania', desc: 'Winter storms, flooding, and severe weather preparedness for Pennsylvania', url: '/guides/emergency-kit-pennsylvania/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Ohio', desc: 'Tornado Alley, flooding, and winter storm preparedness for Ohio', url: '/guides/emergency-kit-ohio/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Georgia', desc: 'Hurricane, tornado, and severe weather preparedness for Georgia', url: '/guides/emergency-kit-georgia/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit North Carolina', desc: 'Hurricanes, mountain weather, and coastal flooding preparedness for NC', url: '/guides/emergency-kit-north-carolina/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Michigan', desc: 'Winter storms, lake-effect snow, and severe weather preparedness for Michigan', url: '/guides/emergency-kit-michigan/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Illinois', desc: 'Tornadoes, severe storms, and Chicago urban emergency preparedness', url: '/guides/emergency-kit-illinois/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Arizona', desc: 'Extreme heat, monsoon flooding, and desert disaster preparedness for Arizona', url: '/guides/emergency-kit-arizona/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Colorado', desc: 'Wildfires, blizzards, and mountain emergency preparedness for Colorado', url: '/guides/emergency-kit-colorado/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Oregon', desc: 'Cascadia earthquake, wildfire, and Pacific Northwest storm preparedness', url: '/guides/emergency-kit-oregon/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Washington', desc: 'Cascadia earthquake, wildfire, and volcanic hazard preparedness for WA', url: '/guides/emergency-kit-washington/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Nevada', desc: 'Desert heat, wildfire, and arid climate disaster preparedness for Nevada', url: '/guides/emergency-kit-nevada/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Utah', desc: 'Wasatch Fault earthquake, wildfire, and mountain desert preparedness', url: '/guides/emergency-kit-utah/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Alaska', desc: 'Extreme cold, earthquakes, and remote wilderness preparedness for Alaska', url: '/guides/emergency-kit-alaska/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Hawaii', desc: 'Tsunami, volcanic eruption, and hurricane preparedness for Hawaii', url: '/guides/emergency-kit-hawaii/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Oklahoma', desc: 'Tornado Alley, severe storms, and wildfire preparedness for Oklahoma', url: '/guides/emergency-kit-oklahoma/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Kansas', desc: 'Tornado Alley, severe weather, and plains state disaster preparedness', url: '/guides/emergency-kit-kansas/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Louisiana', desc: 'Hurricane, catastrophic flooding, and Gulf Coast disaster preparedness', url: '/guides/emergency-kit-louisiana/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Missouri', desc: 'Tornadoes, severe storms, and river flooding preparedness for Missouri', url: '/guides/emergency-kit-missouri/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Virginia', desc: 'Hurricanes, flooding, and coastal storm preparedness for Virginia', url: '/guides/emergency-kit-virginia/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Tennessee', desc: 'Tornadoes, flooding, and severe weather preparedness for Tennessee', url: '/guides/emergency-kit-tennessee/', category: 'State Guides', icon: 'info' },
  { title: 'Emergency Kit Minnesota', desc: 'Extreme cold, blizzards, and severe weather preparedness for Minnesota', url: '/guides/emergency-kit-minnesota/', category: 'State Guides', icon: 'info' },
  { title: 'Best Emergency Kits', desc: 'Top emergency kits compared — buying guide for 72-hour, home, car, and family kits', url: '/guides/best-emergency-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best Car Emergency Kits', desc: 'Roadside survival kits compared — what supplies every vehicle needs', url: '/guides/best-car-emergency-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best Home Emergency Kits', desc: 'Household disaster preparedness kits compared for earthquakes, fires, floods', url: '/guides/best-home-emergency-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best 72-Hour Kits', desc: 'Three-day emergency survival kits compared — portability, contents, shelf life', url: '/guides/best-72-hour-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best Family Emergency Kits', desc: 'Complete household survival kits compared — for families with children, seniors, pets', url: '/guides/best-family-emergency-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best First Aid Kits', desc: 'Emergency medical supplies compared for home, car, and outdoor use', url: '/guides/best-first-aid-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best Emergency Radios', desc: 'NOAA weather radios, hand-crank and solar-powered options compared', url: '/guides/best-emergency-radios/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best Emergency Food Kits', desc: 'Long-term food storage compared — freeze-dried, dehydrated, and MRE options', url: '/guides/best-emergency-food-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best Water Storage Containers', desc: 'Emergency water supply containers compared — barrels, bricks, portable bottles', url: '/guides/best-water-storage-containers/', category: 'Buying Guides', icon: 'info' },
  { title: 'Best Fire Safety Kits', desc: 'Home fire prevention and escape kits compared — extinguishers, alarms, blankets', url: '/guides/best-fire-safety-kits/', category: 'Buying Guides', icon: 'info' },
  { title: 'Emergency Kit vs Survival Kit', desc: 'Key differences in purpose, contents, and use cases between kit types', url: '/guides/emergency-kit-vs-survival-kit/', category: 'Buying Guides', icon: 'info' },
  { title: 'Bug Out Bag vs 72-Hour Kit', desc: 'Compare portability, contents, and use cases for evacuation kits', url: '/guides/bug-out-bag-vs-72-hour-kit/', category: 'Buying Guides', icon: 'info' },
  { title: 'DIY vs Prebuilt Emergency Kit', desc: 'Advantages and disadvantages of building your own kit versus buying pre-assembled', url: '/guides/diy-vs-prebuilt-emergency-kit/', category: 'Buying Guides', icon: 'info' },
  { title: 'Home Kit vs Car Kit', desc: 'Understand differences in contents, purpose, and storage for home and car kits', url: '/guides/home-kit-vs-car-kit/', category: 'Buying Guides', icon: 'info' },
  { title: 'Fire Blanket vs Fire Extinguisher', desc: 'Compare effectiveness, use cases, and safety for different fire types', url: '/guides/fire-blanket-vs-fire-extinguisher/', category: 'Buying Guides', icon: 'info' },
  { title: 'Emergency Radio vs Weather Radio', desc: 'Compare features, reception, and use cases for emergency communication radios', url: '/guides/emergency-radio-vs-weather-radio/', category: 'Buying Guides', icon: 'info' },
  { title: 'Battery Generator vs Gas Generator', desc: 'Compare power output, runtime, safety, and cost of backup power sources', url: '/guides/battery-generator-vs-gas-generator/', category: 'Buying Guides', icon: 'info' },
  { title: 'Bottled Water vs Water Storage', desc: 'Compare convenience, cost, shelf life, and sustainability for emergency water', url: '/guides/bottled-water-vs-water-storage/', category: 'Buying Guides', icon: 'info' },
  { title: 'How to Choose an Emergency Kit', desc: 'Complete buyer decision guide — key factors, common mistakes, step-by-step process', url: '/guides/how-to-choose-an-emergency-kit/', category: 'Buying Guides', icon: 'info' },
  { title: 'Emergency Kit Buying Guide', desc: 'Everything you need to know before buying — what to look for, what to avoid', url: '/guides/emergency-kit-buying-guide/', category: 'Buying Guides', icon: 'info' }
];
