$out = "C:\Users\khalid\OneDrive\Desktop\EmergencyKitGuide\guides\hurricane-emergency-kit\index.html"
$template = Get-Content "C:\Users\khalid\OneDrive\Desktop\EmergencyKitGuide\guides\family-72-hour-emergency-kit\index.html" -Raw
$h = $template.Substring(0, $template.IndexOf('<!-- ARTICLE HERO -->'))
$f = $template.Substring($template.IndexOf('<!-- FOOTER -->'))

$hero = @'
  <!-- ARTICLE HERO -->
  <section class="hero" style="padding-bottom: 40px;">
    <div class="container">
      <div class="hero-content" style="max-width: 800px; margin: 0 auto;">
        <nav style="margin-bottom: 16px; font-size: 14px; color: rgba(255,255,255,0.5);">
          <a href="../../" style="color: rgba(255,255,255,0.6); text-decoration: none;">Home</a>
          <span style="margin: 0 8px;">/</span>
          <a href="../../guides/" style="color: rgba(255,255,255,0.6); text-decoration: none;">Guides</a>
          <span style="margin: 0 8px;">/</span>
          <span style="color: rgba(255,255,255,0.9);">Hurricane Emergency Kit</span>
        </nav>
        <div style="display: inline-flex; align-items: center; gap: 8px; background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; padding: 6px 14px; font-size: 13px; color: rgba(255,255,255,0.7); margin-bottom: 20px;">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>
          13 min read
        </div>
        <h1 class="hero-title" style="font-size: clamp(2rem, 5vw, 3rem); margin-bottom: 16px;">
          Hurricane Emergency Kit: Complete Storm Preparedness Supplies
        </h1>
        <p class="hero-description" style="font-size: 18px; margin-bottom: 20px;">
          Assemble a hurricane emergency kit with enough supplies for 7+ days. Covers water, food, evacuation gear, and storm-specific safety equipment.
        </p>
        <div style="display: flex; align-items: center; gap: 12px; font-size: 13px; color: rgba(255,255,255,0.5);">
          <span>Last updated: July 25, 2025</span>
          <span>By EmergencyKitGuide Editorial Team</span>
        </div>
      </div>
    </div>
  </section>

  <!-- ARTICLE BODY -->
  <section class="section" style="padding-top: 0;">
    <div class="container">
      <div style="display: grid; grid-template-columns: 1fr min(720px, 100%); gap: 48px; align-items: start;">
        <aside style="position: sticky; top: 80px; display: none;" class="toc-sidebar"></aside>
        <article>
'@

$article = @'
          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Why Hurricanes Require 7 Days of Supplies</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Most emergency preparedness guides recommend a 72-hour supply of essentials, but hurricanes demand a fundamentally different approach. When a major hurricane makes landfall, the combination of sustained high winds, catastrophic flooding, and widespread infrastructure damage creates an extended emergency that can last well beyond three days. Power outages after Category 3 and higher hurricanes routinely last two to three weeks. Flooded roads prevent supply trucks from reaching affected communities for five to ten days. Water treatment plants may be offline for over a week, and cell tower damage can leave entire regions without communication for days.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Hurricane Katrina left parts of New Orleans without power for over a month. Hurricane Maria knocked out the entire electrical grid in Puerto Rico for eleven months. Even Hurricane Ian in 2022 left hundreds of thousands of Florida residents without power for more than two weeks. Planning for a minimum of seven days of self-sufficiency gives your family a realistic safety margin during the chaotic period after a hurricane when emergency services are overwhelmed and supply chains are broken. For families in evacuation zones, this extended supply window also provides flexibility if return to your home is delayed beyond initial expectations.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Extended Water Storage for Hurricane Preparedness</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Water is the most critical supply in any hurricane kit, and the quantities needed are significantly larger than for most other disasters. The standard recommendation of one gallon per person per day applies to drinking and basic sanitation, but hurricane conditions often require more. Without air conditioning in subtropical heat, your body demands additional hydration. Flooded homes require extra water for cleaning and hygiene. Contaminated floodwater means you cannot use outdoor water sources for any purpose.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">For a seven-day hurricane supply, plan for two gallons per person per day, which covers drinking, cooking, and basic hygiene. A family of four needs a minimum of 56 gallons. Store water in food-grade plastic containers, commercially bottled water, or large water storage barrels. Fill bathtubs and sinks with water immediately before a hurricane arrives for additional non-potable water used for flushing toilets and cleaning. Include water purification tablets and a portable filter as backup sources if stored water runs low. Our <a href="../../guides/72-hour-water-storage-guide/" style="color: #60a5fa; text-decoration: underline;">72-hour water storage guide</a> covers container options and purification methods in detail.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Boarding Windows: Plywood, Shutters, and Impact Protection</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Flying debris during a hurricane is the leading cause of structural damage and fatalities. Windborne objects can penetrate standard glass windows, allowing rain and wind to enter your home and potentially causing catastrophic structural failure. Protecting your windows before a hurricane arrives is one of the most important preparedness actions you can take. The three primary methods are plywood panels, permanent hurricane shutters, and impact-resistant windows, each with distinct advantages and limitations.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Plywood panels made from five-eighths inch exterior-grade plywood are the most affordable and widely used option. Pre-cut and label each panel for its specific window during the off-season so installation takes minutes rather than hours when a storm approaches. Secure panels with concrete screws driven into the window frame or masonry. Permanent accordion or roll-down shutters offer better protection and faster deployment but cost significantly more. Impact-resistant windows meet Miami-Dade County hurricane standards and eliminate the need for any boarding, though they represent a major investment. Never rely on duct tape or masking tape to protect windows, as this provides zero structural protection against wind and debris. Our <a href="../../guides/home-emergency-kit/" style="color: #60a5fa; text-decoration: underline;">home emergency kit guide</a> includes a complete home hardening checklist.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Evacuation Bag Essentials and Go-Bag Packing</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">When authorities issue a mandatory evacuation order, you may have as little as 24 to 48 hours to prepare and leave. An evacuation bag, also called a go-bag, is a pre-packed container holding the essentials your family needs for several days away from home. Each family member should have their own go-bag in addition to your household's shared hurricane supply kit. The goal is to grab these bags and leave within minutes of deciding to evacuate, without scrambling to collect individual items.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Each go-bag should contain three days of water and food, a change of clothing, sturdy shoes, personal hygiene items, any prescription medications, a flashlight with extra batteries, a portable phone charger, copies of important documents, cash, and a basic first aid kit. Pack items in a waterproof duffel bag or backpack that is easy to carry. Store go-bags in an accessible location, not buried in a closet behind other items. Include comfortable walking shoes in every bag, as you may need to walk long distances if vehicle traffic becomes gridlocked. Our <a href="../../guides/bug-out-bag/" style="color: #60a5fa; text-decoration: underline;">bug out bag guide</a> provides detailed packing lists and recommendations for evacuation scenarios.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Battery-Powered Radio and Storm Tracking</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">A battery-powered or hand-crank NOAA weather radio is arguably the most important single item in a hurricane emergency kit. During and after a hurricane, television broadcasts may be interrupted, internet service may be down, and cell networks may be overwhelmed or damaged. A weather radio provides continuous updates directly from the National Weather Service, including real-time storm tracking, mandatory evacuation orders, shelter locations, and all-clear announcements. This information can be lifesaving when all other communication channels have failed.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Select a radio that receives NOAA Weather Radio All Hazards broadcasts on the 162 MHz frequency band. Models with Specific Area Message Encoding allow you to program your county so the radio only sounds alerts for your location, reducing unnecessary alarm activations. Hand-crank models with built-in USB charging ports serve double duty as both a communication device and a phone charger. Store a generous supply of extra batteries, as a weather radio running continuously during a week-long power outage consumes batteries rapidly. Our <a href="../../guides/emergency-supplies-list/" style="color: #60a5fa; text-decoration: underline;">emergency supplies list</a> includes additional communication gear recommendations.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Document Protection in Waterproof Containers</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Hurricane flooding is the costliest form of natural disaster damage, and water destroys paper documents within hours. Protecting your critical paperwork before a hurricane is essential for insurance claims, identity recovery, and accessing financial resources after the storm. Store original documents in a waterproof, fireproof safe bolted to the floor of your home's highest level. Keep a portable waterproof document bag with copies of the same documents in your evacuation go-bag.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Essential documents include photo identification, insurance policies, birth certificates, social security cards, mortgage or lease agreements, vehicle titles, bank account information, and medical records. Create digital copies of all documents and store them on an encrypted USB drive in your go-bag and in a secure cloud service. Photograph every room of your home before evacuating, including closet and cabinet contents, to document your property for insurance claims. Write down policy numbers, claim phone numbers, and agent contact information on paper, as you may not have internet access to look them up after the storm. Our <a href="../../guides/disaster-preparedness-plan/" style="color: #60a5fa; text-decoration: underline;">disaster preparedness plan</a> includes a complete document protection strategy.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Generator Safety During Extended Power Outages</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Portable generators are invaluable during extended hurricane power outages, providing electricity for refrigeration, medical devices, lighting, and communication equipment. However, generator misuse kills hundreds of people every year, almost exclusively through carbon monoxide poisoning from running generators indoors or too close to the home. Understanding proper generator safety is not optional for hurricane preparedness; it is a matter of life and death.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Place your generator at least 20 feet from your home with the exhaust pointing away from all windows, doors, and vents. Never run a generator in a garage, covered porch, basement, or any enclosed space, even with doors and windows open. Carbon monoxide is colorless and odorless and can reach lethal concentrations in minutes. Never connect a portable generator directly to your home's electrical wiring without a transfer switch installed by a licensed electrician, as this can backfeed electricity onto power lines and kill utility workers. Fill the fuel tank before the hurricane arrives and store extra fuel in approved containers at least 20 feet from any ignition source. Our <a href="../../guides/carbon-monoxide-detector-guide/" style="color: #60a5fa; text-decoration: underline;">carbon monoxide detector guide</a> explains why working detectors are critical when using generators.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Post-Hurricane Cleanup Supplies</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">The danger does not end when the hurricane passes. Post-storm cleanup presents its own set of hazards, including downed power lines, contaminated floodwater, unstable structures, mold growth, and chainsaw injuries. Your hurricane preparedness kit should include cleanup-specific supplies to protect your family during the recovery phase. Heavy-duty work gloves, safety goggles, dust masks, hard hats, and steel-toe boots protect against the most common cleanup injuries.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Pack a chainsaw or hand saw for removing fallen trees, a pry bar for moving debris, heavy-duty trash bags for waste removal, and a tarp for temporary roof repairs. Include bleach for disinfecting flood-damaged surfaces and a pump or wet-dry vacuum for removing standing water from your home. A fire extinguisher should be readily accessible during cleanup, as damaged gas lines and electrical systems create fire risks. Document all damage with photographs before beginning any cleanup or repairs, as this documentation is essential for insurance claims. Our <a href="../../guides/fire-evacuation-plan/" style="color: #60a5fa; text-decoration: underline;">fire evacuation plan</a> covers fire safety considerations during post-hurricane recovery.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Food Supplies for Extended Hurricane Outages</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Extended power outages after a hurricane make refrigerated and frozen food unsafe within hours. Without electricity, a full refrigerator maintains safe temperatures for approximately four hours, and a full freezer for about 48 hours. After that window, perishable food becomes a breeding ground for bacteria that cause foodborne illness. Your hurricane food supply must provide adequate nutrition for seven or more days without any refrigeration or cooking capability.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Focus on shelf-stable items that require no cooking: canned meats, canned fruits and vegetables, peanut butter, crackers, granola bars, nuts, dried fruit, and shelf-stable milk. Include a manual can opener, disposable plates, cups, utensils, and wet wipes. Plan for at least 2,000 calories per adult per day and adjust for children based on age and activity level. Stock specialized items for family members with dietary restrictions, including infant formula, baby food, and nutritional supplements for elderly members. Rotate your hurricane food supply every six to twelve months, checking expiration dates and replacing items that are approaching the end of their shelf life. Our <a href="../../guides/72-hour-emergency-food-list/" style="color: #60a5fa; text-decoration: underline;">72-hour emergency food list</a> provides specific product recommendations and calorie planning worksheets.</p>
'@

$cta = @'
          <div style="background: linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%); border: 1px solid rgba(96,165,250,0.3); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.4rem; margin-bottom: 12px;">Build Your Custom Emergency Kit</h3>
            <p style="color: rgba(255,255,255,0.7); margin-bottom: 20px; max-width: 500px; margin-left: auto; margin-right: auto;">Use our interactive tool to create a personalized emergency kit based on your family size and location.</p>
            <a href="../../tools/emergency-kit-builder/" class="btn btn-accent btn-lg">Open Kit Builder</a>
          </div>
          <div style="background: linear-gradient(135deg, #7f1d1d 0%, #0f172a 100%); border: 1px solid rgba(239,68,68,0.3); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.4rem; margin-bottom: 12px;">Ready-Made Hurricane Kits</h3>
            <p style="color: rgba(255,255,255,0.7); margin-bottom: 20px; max-width: 500px; margin-left: auto; margin-right: auto;">Pre-assembled hurricane emergency kits with extended water supplies, weather radio, and storm-specific gear.</p>
            <a href="https://www.catrunlu.com/5LLufo4FjTH8IAnydMHUmIkUtq82Ou10Y7fYzVH07a_d3WtUW9JOdFSycvlYghTXUTXJAyht43n9GfY5qdDoEA~~/1se" target="_blank" rel="nofollow sponsored noopener" class="btn btn-accent btn-lg">Shop Emergency Kits</a>
          </div>
          <div style="margin: 48px 0;">
            <h2 style="font-size: 1.6rem; font-weight: 700; margin-bottom: 24px; color: #fff;">Frequently Asked Questions</h2>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">How much water should I store for a hurricane?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Store at least two gallons of water per person per day for a minimum of seven days. A family of four needs a minimum of 56 gallons. One gallon is for drinking and the second for sanitation and cooking. Hurricanes can disrupt water treatment plants and break mains for one to two weeks, so the extended supply is critical compared to other disaster types.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">Why should hurricane supplies last 7 days instead of 3?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Hurricanes cause extended infrastructure damage that takes longer to repair than most other disasters. Flooded roads prevent supply trucks from reaching affected areas, power restoration after major hurricanes can take two to three weeks, and water treatment facilities may be offline for over a week. Seven days is the realistic minimum for self-sufficiency.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">Is it safe to use a generator during a hurricane?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Never run a generator indoors, in a garage, or near windows and doors. Generator exhaust contains carbon monoxide, which kills hundreds of people annually. Place generators at least 20 feet from your home with the exhaust pointing away. Never connect a generator to your homes wiring without a transfer switch. Fill the fuel tank before the storm and store extra fuel safely away from the generator.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">When should I evacuate versus shelter in place?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Always follow mandatory evacuation orders. Evacuate if you are in a flood zone, storm surge area, or mobile home. Shelter in place only if you are in a sturdy building outside evacuation zones and authorities have not ordered evacuation. Leave early, as traffic congestion and road closures make late evacuation dangerous.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">What should I do if flooding starts during the hurricane?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Move to the highest level of your home immediately. Never walk, swim, or drive through floodwater. Just six inches of moving water can knock you down and two feet can sweep away a vehicle. If water rises to the first floor, move to the attic or roof and signal for rescue. Avoid contact with floodwater, which may contain sewage, chemicals, and debris.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">How do I prepare my windows for a hurricane?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Plywood panels at least five-eighths inch thick are the most common DIY protection, pre-cut and labeled before hurricane season. Permanent hurricane shutters offer better protection and faster installation. Impact-resistant windows eliminate the need for boarding up. Tape does not prevent windows from breaking and provides a false sense of security. Install protection before tropical storm winds arrive.</div></div>
          </div>
          <div style="background: linear-gradient(135deg, #1a2332 0%, #0f172a 100%); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.3rem; margin-bottom: 8px;">Stay Informed, Stay Prepared</h3>
            <p style="color: rgba(255,255,255,0.6); margin-bottom: 20px;">Get weekly emergency preparedness tips and new guides delivered to your inbox.</p>
            <form class="newsletter-form" style="display: flex; gap: 8px; max-width: 440px; margin: 0 auto;"><input type="email" class="newsletter-input" placeholder="Enter your email" required style="flex: 1; padding: 12px 16px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.15); background: rgba(255,255,255,0.05); color: #fff; font-size: 14px;"><button type="submit" class="btn btn-accent">Subscribe</button></form>
          </div>
          <div style="margin: 48px 0;">
            <h3 style="font-size: 1.3rem; font-weight: 700; color: #fff; margin-bottom: 20px;">Related Guides</h3>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px;">
              <a href="../../guides/hurricane-preparedness-checklist/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #7c3aed; margin-bottom: 8px;">Hurricane Prep</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Hurricane Preparedness Checklist</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Before, during, and after</div></a>
              <a href="../../guides/home-emergency-kit/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #16a34a; margin-bottom: 8px;">Home Safety</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Home Emergency Kit</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Complete household guide</div></a>
              <a href="../../guides/bug-out-bag/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #f97316; margin-bottom: 8px;">Evacuation</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Bug Out Bag Guide</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Grab-and-go essentials</div></a>
            </div>
          </div>
        </article>
      </div>
    </div>
  </section>
'@

$content = $h + $hero + $article + $cta + $f
[System.IO.File]::WriteAllText($out, $content, [System.Text.Encoding]::UTF8)
Write-Output "Written: $out ($($content.Length) chars)"