$out = "C:\Users\khalid\OneDrive\Desktop\EmergencyKitGuide\guides\earthquake-family-plan\index.html"
$template = Get-Content "C:\Users\khalid\OneDrive\Desktop\EmergencyKitGuide\guides\family-72-hour-emergency-kit\index.html" -Raw
$h = $template.Substring(0, $template.IndexOf('<!-- ARTICLE HERO -->'))
$f = $template.Substring($template.IndexOf('<!-- FOOTER -->'))

$hero = @'
  <!-- ARTICLE HERO -->
  <section class="hero" style="padding-bottom: 40px;">
    <div class="container">
      <div class="hero-content" style="max-width: 800px; margin: 0 auto;">
        <nav style="margin-bottom: 16px; font-size: 14px; color: rgba(255,255,255,0.5);">
          <a href="../../" style="color: rgba(255,255,255,0.6); text-decoration: none;">Home</a>
          <span style="margin: 0 8px;">/</span>
          <a href="../../guides/" style="color: rgba(255,255,255,0.6); text-decoration: none;">Guides</a>
          <span style="margin: 0 8px;">/</span>
          <span style="color: rgba(255,255,255,0.9);">Earthquake Family Plan</span>
        </nav>
        <div style="display: inline-flex; align-items: center; gap: 8px; background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; padding: 6px 14px; font-size: 13px; color: rgba(255,255,255,0.7); margin-bottom: 20px;">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>
          12 min read
        </div>
        <h1 class="hero-title" style="font-size: clamp(2rem, 5vw, 3rem); margin-bottom: 16px;">
          Earthquake Family Emergency Plan: Communication and Reunion Strategies
        </h1>
        <p class="hero-description" style="font-size: 18px; margin-bottom: 20px;">
          Create an earthquake family emergency plan with meeting points, communication strategies, and reunion procedures for separated family members.
        </p>
        <div style="display: flex; align-items: center; gap: 12px; font-size: 13px; color: rgba(255,255,255,0.5);">
          <span>Last updated: July 25, 2025</span>
          <span>By EmergencyKitGuide Editorial Team</span>
        </div>
      </div>
    </div>
  </section>

  <!-- ARTICLE BODY -->
  <section class="section" style="padding-top: 0;">
    <div class="container">
      <div style="display: grid; grid-template-columns: 1fr min(720px, 100%); gap: 48px; align-items: start;">
        <aside style="position: sticky; top: 80px; display: none;" class="toc-sidebar"></aside>
        <article>
'@

$article = @'
          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Building Your Family Communication Tree</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">When an earthquake strikes during a typical weekday, family members are scattered across schools, workplaces, and commuting routes. Cell towers become overwhelmed within minutes, text messages may take hours to deliver, and voice calls often fail entirely. A family communication tree is a structured system that ensures every member knows exactly how to check in, who to contact, and what sequence of steps to follow when normal communication channels collapse. Without this plan, families waste precious time trying to reach each other through failed networks while critical decisions go unmade.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Start by creating a physical, laminated contact card for every family member. Include the names and phone numbers of all family members, the designated out-of-area contact, local emergency numbers, and the addresses of both meeting points. Each person should carry this card in their wallet, backpack, or purse at all times. Program the same numbers into every family member's phone as ICE contacts. Establish a rule that text messages are preferred over calls during emergencies, as SMS requires less network bandwidth and often succeeds when voice calls fail. Our <a href="../../guides/family-72-hour-emergency-kit/" style="color: #60a5fa; text-decoration: underline;">family 72-hour emergency kit guide</a> covers additional communication tools to include in your supplies.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">The Out-of-Area Contact Strategy</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">An out-of-area contact serves as the central communication hub for your entire family after a disaster. The principle is simple: long-distance phone calls frequently connect when local networks are congested or damaged, so having someone outside the affected area serve as a message relay dramatically increases the chances that family members can coordinate. After the 1989 Loma Prieta earthquake in San Francisco, residents who used out-of-area contacts reported connecting with family hours before local calls became possible.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Choose a relative or close friend who lives in a different city or state. Brief them on the plan and ensure they understand their role. After an earthquake, each family member calls the out-of-area contact to report their status, location, and any needs. The contact then relays information between family members who cannot reach each other directly. Provide this person with a written list of every family member's phone numbers, workplace addresses, school information, and the family meeting points. Store a backup copy of this information in your <a href="../../guides/72-hour-kit/" style="color: #60a5fa; text-decoration: underline;">72-hour survival kit</a> in case all electronic devices are lost or damaged.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Establishing Neighborhood Meeting Points</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Your family needs two designated meeting points: one close to home and one outside the immediate neighborhood. The primary meeting point should be within a short walking distance of your residence, such as a specific neighbor's front yard, a particular tree in a nearby park, or a distinctive landmark that every family member can find without assistance. This location is where family members gather immediately after an earthquake if everyone is in the vicinity and your home is accessible.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">The secondary meeting point should be outside your immediate neighborhood in case your area is unsafe, on fire, or cordoned off by emergency responders. Choose a location like a community center, a relative's home, or a public building that is structurally sound and easily accessible from multiple directions. Both meeting points must be away from buildings, power lines, and trees that could fall during aftershocks. Walk each family member to both locations and practice the route. Even young children should be able to navigate to the primary meeting point independently. Our <a href="../../guides/home-evacuation-checklist/" style="color: #60a5fa; text-decoration: underline;">home evacuation checklist</a> helps you map these routes systematically.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">School Emergency Plans and Protocols</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Schools are among the most prepared institutions for earthquake response. Most districts conduct regular earthquake drills, maintain emergency supply caches, and have detailed reunification procedures. However, parents must understand that schools will not release children immediately after an earthquake. Staff will follow shelter-in-place protocols until the building is inspected and conditions are safe, and reunification typically follows a structured pickup process designed to ensure every child goes to an authorized adult.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Contact your child's school before earthquake season and request a copy of their emergency response plan. Ask specific questions: does the school shelter in place or evacuate? Where is the reunification pickup location? What identification must you present to collect your child? Who are the authorized pickup persons on file? Provide the school with updated emergency contact information and ensure your child knows the family meeting point in case they cannot be picked up immediately. Never drive to the school during or immediately after an earthquake, as roads may be blocked and your presence can hinder emergency vehicle access.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Workplace Emergency Protocols</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Adults spend a significant portion of their waking hours at work, making workplace earthquake preparedness essential. Before an earthquake occurs, find out what emergency protocols your employer has in place. Identify the safest locations in your office for Drop, Cover, and Hold On, such as under sturdy desks or in interior hallways. Locate the nearest emergency exit and the building's designated assembly area. Know where first aid kits and fire extinguishers are stored.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Keep a small personal emergency kit at your workplace, separate from the one at home. This kit should include sturdy shoes, a dust mask, a flashlight, a whistle, a small first aid kit, a bottle of water, energy bars, a phone charger, and a copy of your family communication card. If your workplace does not have an emergency plan, suggest one to your manager. After an earthquake, do not leave the building unless instructed or unless you observe structural damage, fire, or gas leaks. Follow your employer's evacuation procedures and check in with your out-of-area contact once you are safely outside. Our <a href="../../guides/emergency-preparedness-checklist/" style="color: #60a5fa; text-decoration: underline;">emergency preparedness checklist</a> includes workplace-specific items.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Reunification Procedures for Separated Families</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Family reunification after an earthquake follows a predetermined sequence that every member must know by heart. The process begins the moment shaking stops. Each family member first checks in at the primary meeting point near home. Wait there for a predetermined period, typically one hour. If the rest of the family has not arrived or contacted the out-of-area contact within that time, proceed to the secondary meeting point outside the neighborhood.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">This sequence eliminates the dangerous behavior of family members searching randomly through damaged buildings and debris-strewn streets. Research following major earthquakes consistently shows that organized reunification plans reduce both the time to reunite and the risk of additional injuries. Every family member, including children old enough to walk independently, should carry a laminated card listing the meeting points, the out-of-area contact, and the reunification steps. Practice the complete sequence at least twice per year so it becomes automatic, even under the extreme stress of a real earthquake. Our <a href="../../guides/disaster-preparedness-plan/" style="color: #60a5fa; text-decoration: underline;">disaster preparedness plan</a> provides additional details on family coordination strategies.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Teaching Children Earthquake Safety</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Children process fear and uncertainty differently than adults, and an unprepared child may freeze, hide in a dangerous location, or attempt to run home during an earthquake. Teaching children earthquake safety from an early age transforms them from vulnerable dependents into active participants in the family's emergency response. The goal is to build confidence through knowledge and practice, not to create anxiety about an unlikely event.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Start by explaining earthquakes in age-appropriate terms: the ground shakes sometimes, and here is what we do when it happens. Practice Drop, Cover, and Hold On as a game at home, timing how quickly each child can get under a table. Help children memorize the family meeting point and the out-of-area contact's phone number through repetition and quizzes. Role-play the reunification process so children understand that they should go to the meeting point rather than trying to find their parents independently. Read earthquake preparedness books designed for children and watch age-appropriate educational videos together. Our <a href="../../guides/family-72-hour-emergency-kit/" style="color: #60a5fa; text-decoration: underline;">family 72-hour emergency kit guide</a> includes specific supply recommendations for children of different ages.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Special Needs Family Members and Accessibility</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Families with members who have physical disabilities, cognitive challenges, medical conditions, or age-related limitations must tailor their earthquake plans to address these specific needs. A family member who uses a wheelchair requires an evacuation route that avoids stairs. Someone with a visual impairment needs tactile markers along the path to the meeting point. A person with dementia may not remember the plan independently and may need a designated buddy who stays with them during an emergency.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Create a written individual emergency plan for each family member with special needs. Include their specific medical requirements, medications, equipment, dietary restrictions, and the names and phone numbers of their doctors and caregivers. Store this information in the family emergency kit and provide copies to the out-of-area contact and any trusted neighbors who might assist during an evacuation. Identify accessible evacuation routes from your home and practice them regularly. Ensure that medical equipment, medications, and mobility aids are stored in locations that remain accessible even after structural damage. Our <a href="../../guides/emergency-supplies-list/" style="color: #60a5fa; text-decoration: underline;">emergency supplies list</a> includes accommodation items for family members with diverse needs.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Pet Evacuation Planning for Earthquakes</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Pets are vulnerable during earthquakes and create additional planning considerations. Panicked animals may flee through damaged fences, hide in inaccessible locations, or injure themselves on broken glass. The American Red Cross recommends that pet owners incorporate their animals into every aspect of their family earthquake plan, from the communication tree to the meeting point selection.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Designate a pet-friendly primary meeting point. Keep a collar with current identification tags on every pet at all times and ensure microchip registration is up to date. Store a pet carrier near your main exit so you can secure your animal quickly. Pack a pet emergency kit with at least seven days of food, water, medications, vaccination records, a leash, waste bags, and a comfort item. Research pet-friendly hotels, boarding facilities, and emergency shelters along your evacuation routes before an earthquake occurs. Many Red Cross shelters do not accept animals, so having alternative arrangements prevents the impossible choice between evacuating to safety and staying behind with your pet. Our <a href="../../guides/72-hour-kit/" style="color: #60a5fa; text-decoration: underline;">72-hour survival kit guide</a> includes a complete pet supply checklist.</p>
'@

$cta = @'
          <div style="background: linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%); border: 1px solid rgba(96,165,250,0.3); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.4rem; margin-bottom: 12px;">Build Your Custom Emergency Kit</h3>
            <p style="color: rgba(255,255,255,0.7); margin-bottom: 20px; max-width: 500px; margin-left: auto; margin-right: auto;">Use our interactive tool to create a personalized emergency kit based on your family size and location.</p>
            <a href="../../tools/emergency-kit-builder/" class="btn btn-accent btn-lg">Open Kit Builder</a>
          </div>
          <div style="background: linear-gradient(135deg, #7f1d1d 0%, #0f172a 100%); border: 1px solid rgba(239,68,68,0.3); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.4rem; margin-bottom: 12px;">Ready-Made Emergency Kits</h3>
            <p style="color: rgba(255,255,255,0.7); margin-bottom: 20px; max-width: 500px; margin-left: auto; margin-right: auto;">Pre-assembled emergency kits with communication cards, whistles, and family planning supplies.</p>
            <a href="https://www.catrunlu.com/5LLufo4FjTH8IAnydMHUmIkUtq82Ou10Y7fYzVH07a_d3WtUW9JOdFSycvlYghTXUTXJAyht43n9GfY5qdDoEA~~/1se" target="_blank" rel="nofollow sponsored noopener" class="btn btn-accent btn-lg">Shop Emergency Kits</a>
          </div>
          <div style="margin: 48px 0;">
            <h2 style="font-size: 1.6rem; font-weight: 700; margin-bottom: 24px; color: #fff;">Frequently Asked Questions</h2>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">How do we choose a family meeting point after an earthquake?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Select two meeting points: one close to home for emergencies and one outside the neighborhood for situations where your area is unsafe. Both locations should be easily accessible, well-known to all family members, and away from buildings, power lines, and trees. Practice getting to both locations so everyone can find them without assistance.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">What are my children's school earthquake plans?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Contact your children's school directly to request their emergency response plan. Most schools conduct earthquake drills and have designated reunification procedures. Ask whether students shelter in place or evacuate, where the designated pickup area is located, and what identification you must present to collect your child. Provide the school with your emergency contact information and authorized pickup persons.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">What is an out-of-area emergency contact?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">An out-of-area contact is a friend or relative who lives in a different city or state that all family members call to report their status after a disaster. Long-distance phone calls often connect when local networks are congested or damaged. Choose someone everyone can reach easily and provide them with a written list of all family members' phone numbers.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">How does family reunification work after a major earthquake?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Follow a pre-established reunification sequence: first each person checks in at the neighborhood meeting point. If family members are not there within one hour, proceed to the secondary meeting location. If the secondary location is also empty, contact the out-of-area emergency contact. Each family member should carry a card with the meeting points, contact numbers, and reunification steps.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">How should I prepare young children for an earthquake?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Teach children the Drop, Cover, and Hold On technique through regular practice drills. Use age-appropriate language to explain earthquakes without creating fear. Practice finding safe spots in every room. Help children memorize your family meeting point and the out-of-area contacts phone number. Reassure them that being prepared means they know exactly what to do.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">What should I include in a pet evacuation plan for earthquakes?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Include your pet in your family meeting point plan by designating a pet-friendly location. Keep a collar with ID tags on your pet at all times and have a carrier ready. Pack seven days of pet food, water, medications, vaccination records, and a comfort item. Research pet-friendly shelters along your evacuation routes before an earthquake occurs.</div></div>
          </div>
          <div style="background: linear-gradient(135deg, #1a2332 0%, #0f172a 100%); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.3rem; margin-bottom: 8px;">Stay Informed, Stay Prepared</h3>
            <p style="color: rgba(255,255,255,0.6); margin-bottom: 20px;">Get weekly emergency preparedness tips and new guides delivered to your inbox.</p>
            <form class="newsletter-form" style="display: flex; gap: 8px; max-width: 440px; margin: 0 auto;"><input type="email" class="newsletter-input" placeholder="Enter your email" required style="flex: 1; padding: 12px 16px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.15); background: rgba(255,255,255,0.05); color: #fff; font-size: 14px;"><button type="submit" class="btn btn-accent">Subscribe</button></form>
          </div>
          <div style="margin: 48px 0;">
            <h3 style="font-size: 1.3rem; font-weight: 700; color: #fff; margin-bottom: 20px;">Related Guides</h3>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px;">
              <a href="../../guides/earthquake-emergency-kit/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #f97316; margin-bottom: 8px;">Earthquake Prep</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Earthquake Emergency Kit</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Essential seismic supplies</div></a>
              <a href="../../guides/family-72-hour-emergency-kit/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #2563eb; margin-bottom: 8px;">Family Planning</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Family 72-Hour Kit</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Complete household guide</div></a>
              <a href="../../guides/disaster-preparedness-plan/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #16a34a; margin-bottom: 8px;">Planning</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Disaster Preparedness Plan</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Comprehensive strategy</div></a>
            </div>
          </div>
        </article>
      </div>
    </div>
  </section>
'@

$content = $h + $hero + $article + $cta + $f
[System.IO.File]::WriteAllText($out, $content, [System.Text.Encoding]::UTF8)
Write-Output "Written: $out ($($content.Length) chars)"