$out = "C:\Users\khalid\OneDrive\Desktop\EmergencyKitGuide\guides\hurricane-preparedness-checklist\index.html"
$template = Get-Content "C:\Users\khalid\OneDrive\Desktop\EmergencyKitGuide\guides\family-72-hour-emergency-kit\index.html" -Raw
$h = $template.Substring(0, $template.IndexOf('<!-- ARTICLE HERO -->'))
$f = $template.Substring($template.IndexOf('<!-- FOOTER -->'))

$hero = @'
  <!-- ARTICLE HERO -->
  <section class="hero" style="padding-bottom: 40px;">
    <div class="container">
      <div class="hero-content" style="max-width: 800px; margin: 0 auto;">
        <nav style="margin-bottom: 16px; font-size: 14px; color: rgba(255,255,255,0.5);">
          <a href="../../" style="color: rgba(255,255,255,0.6); text-decoration: none;">Home</a>
          <span style="margin: 0 8px;">/</span>
          <a href="../../guides/" style="color: rgba(255,255,255,0.6); text-decoration: none;">Guides</a>
          <span style="margin: 0 8px;">/</span>
          <span style="color: rgba(255,255,255,0.9);">Hurricane Preparedness Checklist</span>
        </nav>
        <div style="display: inline-flex; align-items: center; gap: 8px; background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; padding: 6px 14px; font-size: 13px; color: rgba(255,255,255,0.7); margin-bottom: 20px;">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>
          12 min read
        </div>
        <h1 class="hero-title" style="font-size: clamp(2rem, 5vw, 3rem); margin-bottom: 16px;">
          Hurricane Preparedness Checklist: Before, During, and After the Storm
        </h1>
        <p class="hero-description" style="font-size: 18px; margin-bottom: 20px;">
          Step-by-step hurricane preparedness checklist for before, during, and after a storm. Covers boarding windows, evacuation, shelter-in-place, and recovery.
        </p>
        <div style="display: flex; align-items: center; gap: 12px; font-size: 13px; color: rgba(255,255,255,0.5);">
          <span>Last updated: July 25, 2025</span>
          <span>By EmergencyKitGuide Editorial Team</span>
        </div>
      </div>
    </div>
  </section>

  <!-- ARTICLE BODY -->
  <section class="section" style="padding-top: 0;">
    <div class="container">
      <div style="display: grid; grid-template-columns: 1fr min(720px, 100%); gap: 48px; align-items: start;">
        <aside style="position: sticky; top: 80px; display: none;" class="toc-sidebar"></aside>
        <article>
'@

$article = @'
          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Pre-Season Preparation: May Through November</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">The Atlantic hurricane season officially runs from June 1 through November 30, with peak activity typically occurring between August and October. Waiting until a storm is named to begin preparations is one of the most dangerous mistakes residents in hurricane-prone areas make. By the time a tropical system is forecast to affect your location, hardware stores are sold out of plywood, gas stations run dry, and traffic gridlock makes evacuation stressful and slow. Effective hurricane preparedness begins months before the first named storm of the season.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Use the early months of hurricane season, May and June, to complete all structural and supply preparations while resources are plentiful and weather is calm. Inspect your roof for loose shingles, clear gutters and drainage paths, trim trees near your home, and test your generator before you need it. Purchase or update your hurricane emergency kit while stores have full inventory. Review your insurance policies to confirm coverage amounts and deductible terms. Our <a href="../../guides/home-emergency-kit/" style="color: #60a5fa; text-decoration: underline;">home emergency kit guide</a> provides a complete home hardening checklist for the pre-season period.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Home Hardening Checklist</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Hardening your home against hurricane damage involves protecting every vulnerable opening and attachment point. Windows and glass doors are the most common entry points for wind and rain, which can pressurize the interior of your home and cause catastrophic roof failure from the inside out. Install plywood panels, permanent shutters, or impact-resistant windows before hurricane season begins. Measure and pre-cut plywood for every window and glass door, label each panel clearly, and store them in an accessible location with the necessary screws and a drill.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Secure outdoor items that can become windborne projectiles: patio furniture, grills, garden tools, garbage cans, and decorative items. These objects cause significant damage when hurled by 100-mile-per-hour winds. Anchor your air conditioning unit if it is not already secured. Inspect and reinforce garage doors, which are a common point of structural failure during hurricanes. Install hurricane straps on your roof if your home does not already have them, as these connectors significantly reduce the risk of roof separation from the walls. Our <a href="../../guides/emergency-preparedness-checklist/" style="color: #60a5fa; text-decoration: underline;">emergency preparedness checklist</a> includes seasonal home maintenance reminders.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Evacuation Route Planning</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Every family living in a hurricane-prone area must identify and practice at least two evacuation routes before storm season begins. Primary routes are the most direct roads to higher ground or inland locations, but these become severely congested during mass evacuations. Secondary and tertiary routes using lesser-known state roads, county roads, and rural highways often move traffic faster when interstates are gridlocked. Map these routes using both GPS and paper maps, as cell service and GPS may be unreliable during an evacuation.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Identify destinations along each route: friends or family who can host you, hotels outside the evacuation zone, or public shelters designated by your county emergency management agency. Fill your vehicle's gas tank when a storm is forecast to affect your area, as gas stations along evacuation routes run out quickly. Keep your vehicle's emergency kit stocked and accessible. Our <a href="../../guides/car-emergency-kit/" style="color: #60a5fa; text-decoration: underline;">car emergency kit guide</a> covers the specific supplies you need for hurricane evacuations by vehicle.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Shelter-in-Place Procedures</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Sheltering in place is appropriate only when you live in a sturdy structure outside designated evacuation zones and authorities have not ordered evacuation. The safest room in your home during a hurricane is an interior room on the lowest level that has no windows, such as a bathroom, closet, or hallway. This room should serve as your family's designated storm shelter where everyone gathers when winds reach tropical storm force.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Before the storm arrives, move your hurricane emergency kit, water, food, and comfort items into the shelter room. Fill sinks and bathtubs with water for emergency flushing and cleaning. Charge all phones, tablets, and portable chargers to full capacity. Turn your refrigerator and freezer to the coldest settings to extend food preservation during the expected power outage. Turn off utilities if instructed by authorities. Keep shoes on and stay away from all windows throughout the storm. Our <a href="../../guides/home-evacuation-checklist/" style="color: #60a5fa; text-decoration: underline;">home evacuation checklist</a> includes shelter-in-place preparation steps.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">During the Storm: Safety Protocols</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">During the hurricane itself, your primary objective is survival. Stay in your designated interior shelter room and keep all family members together. Do not go outside to observe the storm, even during apparent lulls. The eye of a hurricane can pass over your location, creating a period of calm winds followed immediately by the return of the storm's back side with winds from the opposite direction. This false sense of safety has caused numerous fatalities throughout hurricane history.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">If you hear a roaring sound or feel a sudden drop in air pressure, the storm may be intensifying or a tornado may be forming within the hurricane's outer bands. Move to the most interior portion of your shelter room and cover yourself with a mattress, heavy blankets, or sleeping bags for protection from debris. Keep your NOAA weather radio on to receive updates from the National Weather Service. If your home sustains structural damage during the storm, move to the area of the structure that remains intact and continue sheltering until conditions improve. Our <a href="../../guides/fire-blanket-guide/" style="color: #60a5fa; text-decoration: underline;">fire blanket guide</a> covers additional protective measures for fire risks associated with storm damage.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Post-Storm Assessment and Safety</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">After the storm passes, wait for official all-clear announcements before leaving your shelter room. The period immediately after a hurricane is deceptively dangerous. Downed power lines may be hidden under standing water, structural damage may not be immediately visible, and weakened trees can fall hours after the wind subsides. Put on sturdy shoes, long pants, and work gloves before walking through your home or neighborhood. Check for injuries among family members and administer first aid as needed.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Inspect your home systematically for gas leaks, electrical damage, and structural compromise. If you smell natural gas, hear hissing near gas lines, or see damaged piping, leave the building immediately and do not re-enter until a professional has cleared it. Take photographs of all damage before moving anything, as this documentation is critical for insurance claims. Contact your out-of-area emergency contact to report your status. Listen to NOAA weather radio and local emergency broadcasts for information about road closures, shelter locations, and utility restoration timelines. Our <a href="../../guides/emergency-supplies-list/" style="color: #60a5fa; text-decoration: underline;">emergency supplies list</a> includes post-storm cleanup gear.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Insurance Documentation and FEMA Assistance</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Proper insurance documentation before a hurricane is just as important as physical preparedness. Standard homeowners insurance covers wind damage but typically excludes flood damage. If you live in a FEMA-designated flood zone, you are required to carry flood insurance through the National Flood Insurance Program. Even if you are not in a designated zone, consider supplemental flood coverage, as hurricanes can produce catastrophic flooding well beyond traditional flood maps.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Before hurricane season, review your policy limits, deductible amounts, and coverage exclusions. Create a comprehensive home inventory with photographs and video of every room. Store this inventory on a cloud service, on an encrypted USB drive, and in a waterproof document bag in your evacuation kit. After a hurricane, file insurance claims as soon as possible, as processing times increase dramatically when thousands of claims arrive simultaneously. If you suffer significant damage, you may also be eligible for FEMA Individual Assistance grants. Apply through DisasterAssistance.gov or by calling FEMA's toll-free number. Our <a href="../../guides/disaster-preparedness-plan/" style="color: #60a5fa; text-decoration: underline;">disaster preparedness plan</a> includes a complete insurance review checklist.</p>

          <h2 style="font-size: 1.6rem; font-weight: 700; margin: 40px 0 16px; color: #fff;">Mold Prevention After Flooding</h2>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Mold growth is one of the most persistent and health-threatening consequences of hurricane flooding. Mold can begin growing on wet surfaces within 24 to 48 hours, and once established, it spreads rapidly through porous materials like drywall, carpet, insulation, and ceiling tiles. The Centers for Disease Control and Prevention warns that mold exposure can cause respiratory problems, allergic reactions, and worsen symptoms in people with asthma or compromised immune systems. Rapid response to water intrusion is essential to prevent a manageable water problem from becoming a months-long mold remediation project.</p>
          <p style="color: rgba(255,255,255,0.7); line-height: 1.8; margin-bottom: 16px;">Begin removing standing water as soon as it is safe to do so. Open windows and doors to promote air circulation, and use fans and dehumidifiers to dry interior spaces. Remove saturated carpet, padding, and drywall that cannot be dried within 48 hours. Clean hard surfaces with a solution of one cup of bleach per gallon of water to kill mold spores. Wear an N95 respirator mask, gloves, and eye protection during cleanup, as disturbed mold releases spores that can cause serious respiratory illness. Take photographs of all damage and removed materials for insurance documentation before discarding anything. Our <a href="../../guides/smoke-alarm-maintenance/" style="color: #60a5fa; text-decoration: underline;">smoke alarm maintenance guide</a> covers post-flood alarm testing and replacement procedures.</p>
'@

$cta = @'
          <div style="background: linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%); border: 1px solid rgba(96,165,250,0.3); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.4rem; margin-bottom: 12px;">Build Your Custom Emergency Kit</h3>
            <p style="color: rgba(255,255,255,0.7); margin-bottom: 20px; max-width: 500px; margin-left: auto; margin-right: auto;">Use our interactive tool to create a personalized emergency kit based on your family size and location.</p>
            <a href="../../tools/emergency-kit-builder/" class="btn btn-accent btn-lg">Open Kit Builder</a>
          </div>
          <div style="background: linear-gradient(135deg, #7f1d1d 0%, #0f172a 100%); border: 1px solid rgba(239,68,68,0.3); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.4rem; margin-bottom: 12px;">Ready-Made Emergency Kits</h3>
            <p style="color: rgba(255,255,255,0.7); margin-bottom: 20px; max-width: 500px; margin-left: auto; margin-right: auto;">Pre-assembled emergency kits with all the essentials. A convenient option for families who want to be prepared fast.</p>
            <a href="https://www.catrunlu.com/5LLufo4FjTH8IAnydMHUmIkUtq82Ou10Y7fYzVH07a_d3WtUW9JOdFSycvlYghTXUTXJAyht43n9GfY5qdDoEA~~/1se" target="_blank" rel="nofollow sponsored noopener" class="btn btn-accent btn-lg">Shop Emergency Kits</a>
          </div>
          <div style="margin: 48px 0;">
            <h2 style="font-size: 1.6rem; font-weight: 700; margin-bottom: 24px; color: #fff;">Frequently Asked Questions</h2>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">When should I start preparing for hurricane season?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Begin preparations in May, before the official start of June 1 hurricane season. Complete home hardening, supply purchases, insurance reviews, and evacuation route mapping while stores have inventory and weather is calm. Waiting until a storm is named leaves you competing for dwindling supplies with millions of other residents.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">Should I board up my windows with plywood or install shutters?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Plywood is the most affordable option and provides adequate protection when properly installed with concrete screws. Permanent shutters offer faster deployment and better protection but cost more upfront. Impact-resistant windows eliminate boarding entirely but represent the highest initial investment. Choose based on your budget, how often you face hurricane threats, and how quickly you need to protect your home.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">How do I know if I am in an evacuation zone?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Check your county emergency management agency website for evacuation zone maps. These maps divide areas into zones based on storm surge risk. Know your zone letter before hurricane season begins. When authorities issue evacuation orders, they reference these zones by letter. You can also call your local emergency management office to confirm your zone designation.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">What should I do during the hurricane?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Stay in your designated interior shelter room away from all windows. Keep your NOAA weather radio on for updates. Never go outside to observe the storm, even during calm periods in the eye. If you hear a sudden roar or feel pressure changes, move to the most interior space and cover yourself with a mattress or heavy blankets. Stay sheltered until official all-clear announcements.</div></div>
            <div style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 12px; overflow: hidden;"><div style="padding: 16px 20px; background: rgba(255,255,255,0.03); cursor: pointer;"><strong style="color: #fff;">What are the first steps after a hurricane passes?</strong></div><div style="padding: 0 20px 16px; color: rgba(255,255,255,0.7); line-height: 1.8;">Wait for official all-clear before moving. Check for injuries and administer first aid. Inspect your home for gas leaks, structural damage, and electrical hazards. Put on sturdy shoes and gloves. Document all damage with photographs before cleaning. Contact your out-of-area emergency contact. Listen to local emergency broadcasts for road and shelter information. Begin removing standing water within 24 hours to prevent mold growth.</div></div>
          </div>
          <div style="background: linear-gradient(135deg, #1a2332 0%, #0f172a 100%); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 32px; margin: 48px 0; text-align: center;">
            <h3 style="color: #fff; font-size: 1.3rem; margin-bottom: 8px;">Stay Informed, Stay Prepared</h3>
            <p style="color: rgba(255,255,255,0.6); margin-bottom: 20px;">Get weekly emergency preparedness tips and new guides delivered to your inbox.</p>
            <form class="newsletter-form" style="display: flex; gap: 8px; max-width: 440px; margin: 0 auto;"><input type="email" class="newsletter-input" placeholder="Enter your email" required style="flex: 1; padding: 12px 16px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.15); background: rgba(255,255,255,0.05); color: #fff; font-size: 14px;"><button type="submit" class="btn btn-accent">Subscribe</button></form>
          </div>
          <div style="margin: 48px 0;">
            <h3 style="font-size: 1.3rem; font-weight: 700; color: #fff; margin-bottom: 20px;">Related Guides</h3>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px;">
              <a href="../../guides/hurricane-emergency-kit/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #7c3aed; margin-bottom: 8px;">Hurricane Prep</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Hurricane Emergency Kit</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">7+ days of storm supplies</div></a>
              <a href="../../guides/home-evacuation-checklist/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #16a34a; margin-bottom: 8px;">Home Safety</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Home Evacuation Checklist</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Escape planning steps</div></a>
              <a href="../../guides/disaster-preparedness-plan/" style="display: block; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; text-decoration: none;"><div style="font-size: 12px; color: #2563eb; margin-bottom: 8px;">Planning</div><div style="font-weight: 600; color: #fff; margin-bottom: 6px;">Disaster Preparedness Plan</div><div style="font-size: 13px; color: rgba(255,255,255,0.5);">Comprehensive strategy</div></a>
            </div>
          </div>
        </article>
      </div>
    </div>
  </section>
'@

$content = $h + $hero + $article + $cta + $f
[System.IO.File]::WriteAllText($out, $content, [System.Text.Encoding]::UTF8)
Write-Output "Written: $out ($($content.Length) chars)"